export default {
  Rental: 'Rental',
  ProductDetails: 'ProductDetails',
  Cart: 'Cart',
  Checkout: 'Checkout',
  Profile: 'Profile',
  Cards: 'Cards',
  Receipt: 'Receipt',
  Products: 'Products',
  Splash: 'Splash',
  FullMapView: 'FullMapView',
  RestPassword: 'RestPassword',
  OrderHistory: 'OrderHistory',
  Signup: 'Signup',
};
