import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  DISABLED,
  Helvetica_Neue_Bold,
  Helvetica_Neue_BoldCondensed,
  Helvetica_Neue_Heavy,
  Helvetica_Neue_Italic,
  Helvetica_Neue_Light,
  Helvetica_Neue_Medium,
  LIGHT_THEME,
  PRIMARY_PURPLE,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
  },
  scrollContainer: {
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: 'auto',
  },
  headerContainer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.17,
    elevation: 6,
    justifyContent: 'flex-end',
  },
  headerBackIconContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.04,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'center',
    // backgroundColor: 'green',
    marginRight: 50,
  },
  headerTextContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.08,
    justifyContent: 'center',
    alignSelf: 'center',
    //     backgroundColor: 'tomato',
    marginRight: 30,
  },
  headerText: {
    fontSize: 35,
    fontFamily: Helvetica_Neue_Heavy,
    color: DARK_THEME,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  pickupDetails: {
    backgroundColor: DARK_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.07,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
  },
  upperTextContainer: {
    // backgroundColor: 'tomato',
    alignSelf: 'center',
    width: windowWidth * 0.9,
    alignItems: 'flex-start',
  },
  upperText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 14,
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
    color: LIGHT_THEME,
  },
  lowerTextContainer: {
    flexDirection: 'row',
    // backgroundColor: 'tomato',
    alignSelf: 'center',
    width: windowWidth * 0.9,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  lowerText: {
    fontFamily: Helvetica_Neue_Medium,
    fontSize: 16,
    // backgroundColor: 'green',
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
    color: LIGHT_THEME,
  },
  cartSummaryContainer: {
    backgroundColor: LIGHT_THEME,
    elevation: 3,
    height: windowHeight * 0.45,
    width: windowWidth * 0.95,
    borderRadius: 20,
    marginTop: 30,
    justifyContent: 'space-around',
  },
  imageNameContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.95,
    height: windowHeight * 0.12,
    flexDirection: 'row',
  },
  imageContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.4,
    height: windowHeight * 0.12,
  },
  imageStyles: {
    // backgroundColor: 'green',
    width: windowWidth * 0.4,
    height: windowHeight * 0.12,
  },
  nameDescContainer: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.55,
    height: windowHeight * 0.12,
    alignItems: 'flex-start',
    justifyContent: 'space-evenly',
  },
  productNameTextContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.55,
    height: windowHeight * 0.03,
    justifyContent: 'center',
  },
  productNameText: {
    fontFamily: Helvetica_Neue_Medium,
    fontSize: 16,
    textAlign: 'left',
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  productDescText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 14,
    textAlign: 'left',
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  productDescTextContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.55,
    height: windowHeight * 0.07,
    justifyContent: 'center',
  },
  brandTypeContainer: {
    // backgroundColor: 'red',
    width: windowWidth * 0.95,
    height: windowHeight * 0.14,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  brandType1: {
    width: windowWidth * 0.26,
    height: windowHeight * 0.1,
    backgroundColor: LIGHT_THEME,
    borderRadius: 10,
    elevation: 4,
    borderColor: PRIMARY_PURPLE,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandType2: {
    width: windowWidth * 0.26,
    height: windowHeight * 0.1,
    backgroundColor: LIGHT_THEME,
    borderRadius: 10,
    elevation: 4,
    // borderColor: PRIMARY_PURPLE,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandType3: {
    width: windowWidth * 0.26,
    height: windowHeight * 0.1,
    backgroundColor: LIGHT_THEME,
    borderRadius: 10,
    elevation: 4,
    // borderColor: PRIMARY_PURPLE,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandNameText: {
    fontFamily: Helvetica_Neue_Bold,
    color: DARK_THEME,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    // lineHeight: 20,
  },
  brandPriceText: {
    fontFamily: Helvetica_Neue_Bold,
    color: PRIMARY_PURPLE,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  breaker: {
    backgroundColor: '#DADADA',
    width: windowWidth * 0.85,
    height: 1,
    // marginTop: windowHeight * 0.02,
    alignSelf: 'center',
  },
  totalPriceContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.95,
    height: windowHeight * 0.07,
    alignSelf: 'center',
    justifyContent: 'space-evenly',
  },
  totalPrice: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  totalPriceText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 16,
    textAlign: 'left',
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  priceContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  PriceText: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 20,
    textAlign: 'left',
    textAlignVertical: 'center',
    color: PRIMARY_PURPLE,
  },
  counterContainer: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    width: windowWidth * 0.2,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  grandTotalContainer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 0.95,
    height: windowHeight * 0.2,
    elevation: 4,
    borderRadius: 20,
    marginTop: 20,
    justifyContent: 'center',
  },
  subContainer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    height: windowHeight * 0.03,
    alignSelf: 'center',
  },
  subtotalText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 16,
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  totalCost: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 20,
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  breaker2: {
    backgroundColor: PRIMARY_PURPLE,
    width: windowWidth * 0.8,
    height: 2,
    marginTop: windowHeight * 0.01,
    marginBottom: windowHeight * 0.01,
    alignSelf: 'center',
  },
  customButton: {
    backgroundColor: DARK_THEME,
    height: windowHeight * 0.07,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    marginTop: windowHeight * 0.04,
    alignSelf: 'center',
    elevation: 3,
    marginBottom: windowHeight * 0.01,
  },
  customButtonText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  headingContainer: {
    // backgroundColor: 'tomato',
    marginTop: windowHeight * 0.02,
    width: windowWidth * 0.9,
  },
  heading: {
    fontFamily: Helvetica_Neue_Medium,
    color: DARK_THEME,
    fontSize: 20,
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
  },
  emptySignContainer: {
    // backgroundColor: 'tomato',
    width: '100%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    // flex: 1,
    alignSelf: 'center',
  },
  cartEmptySlogan: {
    // backgroundColor: 'tomato',
    width: windowHeight * 0.3,
    alignItems: 'center',
    marginTop: windowHeight * 0.03,
    height: 'auto',
  },
  cartEmptySloganText: {
    fontFamily: Helvetica_Neue_Light,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    height: 'auto',
    color: DISABLED,
  },
  cartImageStyles: {
    // backgroundColor: 'tomato',
    alignSelf: 'center',
    justifyContent: 'center',
  },
});

export default styles;
