import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  Helvetica_Neue_Heavy,
  Helvetica_Neue_Medium,
  Helvetica_Neue_BoldCondensed,
  LIGHT_THEME,
  INPUT_BORDER_COLOR,
  Helvetica_Neue_Light,
  PRIMARY_PURPLE,
  Helvetica_Neue_Bold,
  DISABLED,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    // justifyContent: 'center',
    width: windowWidth * 1.0,
    height: windowHeight * 1.0,
    alignItems: 'center',
    backgroundColor: LIGHT_THEME,
  },
  scrollContainer: {
    marginTop: 1,
    alignItems: 'center',
    backgroundColor: LIGHT_THEME,
  },
  headerContainer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.17,
    elevation: 6,
    justifyContent: 'flex-end',
  },
  headerBackIconContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.04,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'center',
    //     backgroundColor: 'green',
    marginRight: 50,
  },
  headerTextContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.08,
    justifyContent: 'center',
    alignSelf: 'center',
    //     backgroundColor: 'tomato',
    marginRight: 30,
  },
  headerText: {
    fontSize: 35,
    fontFamily: Helvetica_Neue_Heavy,
    color: DARK_THEME,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  ImageSwiperContainer: {
    //     backgroundColor: 'tomato',
    width: windowWidth * 1.0,
    height: windowHeight * 0.3,
    marginTop: 1,
  },
  imageSwiper: {
    // backgroundColor: 'gold',
    width: windowWidth * 1.0,
    height: windowHeight * 0.3,
    //     borderRadius: 10,
    elevation: 5,
  },
  dotStyle: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: windowHeight * 0.02,
    alignSelf: 'center',
    justifyContent: 'space-around',
    // backgroundColor: 'tomato',
    width: windowWidth * 0.1,
    color: 'dodgeblue',
  },
  pagingText: {
    color: '#888',
    fontSize: 16,
    opacity: 0.1,
  },
  pagingActiveText: {
    color: '#14213D',
    fontSize: 16,
  },
  ProductDetailsContainer: {
    // backgroundColor: 'tomato',
    height: windowHeight * 0.23,
    width: windowWidth * 0.95,
    justifyContent: 'space-between',
  },
  nameAndReviewContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // backgroundColor: 'green',
    alignItems: 'center',
    width: windowWidth * 0.95,
    height: 'auto',
    alignSelf: 'center',
  },
  nameTextContainer: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.4,
    height: 'auto',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  subject: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.95,
    height: 'auto',
    alignItems: 'flex-start',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  nameText: {
    fontFamily: Helvetica_Neue_Medium,
    color: DARK_THEME,
    fontSize: 17,
    textAlign: 'left',
  },
  reviewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.23,
    height: windowHeight * 0.04,
  },
  descriptionContainer: {
    // backgroundColor: 'green',
    height: 'auto',
    width: windowWidth * 0.95,
    alignSelf: 'center',
  },
  descriptionText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 16,
    textAlignVertical: 'center',
    textAlign: 'left',
    color: DARK_THEME,
  },
  reviewdescriptionContainer: {
    // backgroundColor: 'green',
    height: 'auto',
    width: windowWidth * 0.95,
    alignSelf: 'center',
  },
  whatInsdeContainer: {
    //     backgroundColor: 'tomato',
    height: windowHeight * 0.05,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  breaker: {
    backgroundColor: '#DADADA',
    width: windowWidth * 0.9,
    height: 1,
    marginTop: windowHeight * 0.05,
  },
  quantityContainer: {
    //     backgroundColor: 'tomato',
    width: windowWidth * 0.9,
    alignItems: 'flex-start',
    justifyContent: 'center',
    alignSelf: 'center',
    margin: 10,
  },
  inputContainer: {
    borderRadius: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    height: windowHeight * 0.05,
    width: windowWidth * 0.3,
    borderWidth: 0.5,
    borderColor: INPUT_BORDER_COLOR,
  },
  dropdown: {
    height: 30,
    borderRadius: 7,
    paddingHorizontal: 17,
    backgroundColor: LIGHT_THEME,
    // elevation: 1,
    width: windowWidth * 0.23,
    alignSelf: 'center',
  },
  placeholderStyle: {
    fontSize: 18,
    fontFamily: Helvetica_Neue_BoldCondensed,
    color: '#737373',
  },
  selectedTextStyle: {
    fontSize: 18,
    fontFamily: Helvetica_Neue_BoldCondensed,
    color: '#737373',
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  containerrrrStyle: {
    marginTop: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 100,
    elevation: 10,
  },
  inputIconContainer: {
    //     backgroundColor: 'tomato',
    height: 20,
    width: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  customButton: {
    backgroundColor: DARK_THEME,
    height: windowHeight * 0.07,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    marginTop: windowHeight * 0.03,
    alignSelf: 'center',
    elevation: 3,
  },
  customButtonText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  publicReviewsContainer: {
    // backgroundColor: 'tomato',
    height: windowHeight * 0.5,
    width: windowWidth * 0.95,
    marginBottom: windowHeight * 0.05,
    marginTop: windowHeight * 0.03,
  },
  userReviewContainer: {
    // backgroundColor: 'tomato',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: 10,
    width: windowWidth * 0.95,
    height: windowHeight * 0.12,
  },
  logoNameAndDateContainer: {
    // backgroundColor: 'gold',
    flexDirection: 'row',
    width: windowWidth * 0.37,
    height: 'auto',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'flex-start',
    alignContent: 'flex-start',
  },
  UserNameText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 13,
    color: DARK_THEME,
  },
  userReviewDate: {
    fontFamily: Helvetica_Neue_Light,
    fontSize: 13,
    color: DARK_THEME,
  },
  hoverPriceContainer: {
    position: 'absolute',
    backgroundColor: PRIMARY_PURPLE,
    width: 100,
    height: 40,
    top: 200,
    left: 325,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 20,
  },
  hoverPriceText: {
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: Helvetica_Neue_Medium,
    fontSize: 20,
    color: LIGHT_THEME,
  },
  counterContainer: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    width: windowWidth * 0.3,
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: 10,
    borderRadius: 6,
    borderWidth: 0.3,
    borderColor: DARK_THEME,
  },
  PriceText: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 19,
    textAlign: 'left',
    textAlignVertical: 'center',
    color: PRIMARY_PURPLE,
  },
  brandTypeContainer: {
    // backgroundColor: 'red',
    width: windowWidth * 0.95,
    height: windowHeight * 0.14,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  brandType1: {
    width: windowWidth * 0.26,
    height: windowHeight * 0.1,
    backgroundColor: LIGHT_THEME,
    borderRadius: 10,
    elevation: 4,
    borderColor: PRIMARY_PURPLE,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandType2: {
    width: windowWidth * 0.26,
    height: windowHeight * 0.1,
    backgroundColor: LIGHT_THEME,
    borderRadius: 10,
    elevation: 4,
    // borderColor: PRIMARY_PURPLE,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandType3: {
    width: windowWidth * 0.26,
    height: windowHeight * 0.1,
    backgroundColor: LIGHT_THEME,
    borderRadius: 10,
    elevation: 4,
    // borderColor: PRIMARY_PURPLE,
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandNameText: {
    fontFamily: Helvetica_Neue_Bold,
    color: DARK_THEME,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    // lineHeight: 20,
  },
  brandPriceText: {
    fontFamily: Helvetica_Neue_Bold,
    color: PRIMARY_PURPLE,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  ratedStyles: {
    backgroundColor: 'tomato',
    marginRight: 320,
  },
});

export default styles;
