import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  DISABLED,
  Helvetica_Neue_Bold,
  Helvetica_Neue_BoldCondensed,
  Helvetica_Neue_Light,
  Helvetica_Neue_Medium,
  LIGHT_THEME,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
  },
  superInputContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.9,
    height: windowHeight * 0.085,
    justifyContent: 'center',
    marginTop: windowHeight * 0.03,
  },
  inputLabelContainer: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.6,
  },
  inputLabelText: {
    fontFamily: Helvetica_Neue_Light,
    fontSize: 14,
    color: DISABLED,
  },
  //   ProfileInputContainer: {
  //     // backgroundColor: 'tomato',
  //     width: windowWidth * 0.9,
  //     height: windowHeight * 0.4,
  //     marginTop: windowHeight * 0.03,
  //     alignItems: 'center',
  //     justifyContent: 'space-evenly',
  //   },
  inputContainer: {
    // borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: windowHeight * 0.05,
    width: windowWidth * 0.9,
    borderBottomWidth: 1,
    borderBottomColor: DISABLED,
    // backgroundColor: 'tomato',
  },
  inputStyle: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 18,
    // backgroundColor: 'tomato',
    width: windowWidth * 0.9,
    color: DARK_THEME,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  customButton: {
    backgroundColor: DARK_THEME,
    height: windowHeight * 0.07,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    marginTop: windowHeight * 0.04,
    alignSelf: 'center',
    elevation: 3,
  },
  customButtonText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  authModalContainer: {
    backgroundColor: LIGHT_THEME,
    alignSelf: 'center',
    width: windowWidth * 0.95,
    height: windowHeight * 0.3,
    borderRadius: 20,
    // position: 'absolute',
    // top: (windowHeight * 1.0) / 4,
    // bottom: (windowHeight * 1.0) / 4,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 40,
    padding: 40,
  },
  OkayTextContainer: {
    backgroundColor: DARK_THEME,
    height: windowHeight * 0.07,
    width: windowWidth * 0.3,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    marginTop: windowHeight * 0.04,
    alignSelf: 'center',
    elevation: 3,
  },
  OkayText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  modalDescription: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  errorMessageTextStyle: {
    color: 'red',
    textAlign: 'left',
    // backgroundColor: 'gold',
    width: windowWidth * 0.9,
    fontFamily: Helvetica_Neue_BoldCondensed,
    alignSelf: 'center',
    fontSize: 12,
    marginTop: 4,
  },
});

export default styles;
