import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  DISABLED,
  Helvetica_Neue_BoldCondensed,
  Helvetica_Neue_Heavy,
  Helvetica_Neue_Light,
  Helvetica_Neue_Medium,
  INPUT_BORDER_COLOR,
  LIGHT_THEME,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
  },
  headerContainer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.17,
    elevation: 6,
    justifyContent: 'flex-end',
  },
  headerBackIconContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.04,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'center',
    //     backgroundColor: 'green',
    marginRight: 50,
  },
  headerTextContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.08,
    justifyContent: 'center',
    alignSelf: 'center',
    //     backgroundColor: 'tomato',
    marginRight: 30,
  },
  headerText: {
    fontSize: 35,
    fontFamily: Helvetica_Neue_Heavy,
    color: DARK_THEME,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  inputContainer: {
    // borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: windowHeight * 0.05,
    width: windowWidth * 0.9,
    borderBottomWidth: 1,
    borderBottomColor: DISABLED,
    // backgroundColor: 'tomato',
  },
  inputStyle: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 18,
    // backgroundColor: 'tomato',
    width: windowWidth * 0.9,
    color: DARK_THEME,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  superInputContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.9,
    height: windowHeight * 0.085,
    justifyContent: 'center',
  },
  inputLabelContainer: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.6,
  },
  inputLabelText: {
    fontFamily: Helvetica_Neue_Light,
    fontSize: 14,
    color: DISABLED,
  },
  ProfileInputContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.9,
    height: windowHeight * 0.4,
    marginTop: windowHeight * 0.03,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  customButton: {
    backgroundColor: DARK_THEME,
    height: windowHeight * 0.07,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    marginTop: windowHeight * 0.04,
    alignSelf: 'center',
    elevation: 3,
  },
  customButtonText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  authModalContainer: {
    backgroundColor: LIGHT_THEME,
    alignSelf: 'center',
    width: windowWidth * 0.95,
    height: windowHeight * 0.6,
    borderRadius: 20,
    // position: 'absolute',
    // top: (windowHeight * 1.0) / 4,
    // bottom: (windowHeight * 1.0) / 4,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 40,
  },
});

export default styles;
