import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  DISABLED,
  Helvetica_Neue_Bold,
  Helvetica_Neue_BoldCondensed,
  Helvetica_Neue_Heavy,
  Helvetica_Neue_Medium,
  Helvetica_Neue_Regular,
  INPUT_BORDER_COLOR,
  LIGHT_THEME,
  PRIMARY_PURPLE,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
  },
  scrollContainer: {
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: 'auto',
  },
  headingContainer: {
    // backgroundColor: 'tomato',
    marginTop: windowHeight * 0.02,
    width: windowWidth * 0.9,
  },
  heading: {
    fontFamily: Helvetica_Neue_Medium,
    color: DARK_THEME,
    fontSize: 20,
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
  },
  headerContainer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.17,
    elevation: 6,
    justifyContent: 'flex-end',
  },
  headerBackIconContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.04,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'center',
    // backgroundColor: 'green',
    marginRight: 50,
  },
  headerTextContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.08,
    justifyContent: 'center',
    alignSelf: 'center',
    //     backgroundColor: 'tomato',
    marginRight: 30,
  },
  headerText: {
    fontSize: 35,
    fontFamily: Helvetica_Neue_Heavy,
    color: DARK_THEME,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  pickupDetails: {
    backgroundColor: DARK_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.07,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
  },
  upperTextContainer: {
    // backgroundColor: 'tomato',
    alignSelf: 'center',
    width: windowWidth * 0.9,
    alignItems: 'flex-start',
  },
  upperText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 14,
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
    color: LIGHT_THEME,
  },
  lowerTextContainer: {
    flexDirection: 'row',
    // backgroundColor: 'tomato',
    alignSelf: 'center',
    width: windowWidth * 0.9,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  lowerText: {
    fontFamily: Helvetica_Neue_Medium,
    fontSize: 16,
    // backgroundColor: 'green',
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
    color: LIGHT_THEME,
  },
  isignupCheckContainer: {
    backgroundColor: LIGHT_THEME,
    height: windowHeight * 0.2,
    width: windowWidth * 0.95,
    elevation: 4,
    borderRadius: 20,
    marginTop: windowHeight * 0.02,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  stylesisignupCheckText: {
    fontFamily: Helvetica_Neue_Medium,
    color: DARK_THEME,
    width: windowWidth * 0.7,
    alignSelf: 'center',
    fontSize: 16,
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
    // backgroundColor: 'tomato',
  },
  authButtonText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    color: PRIMARY_PURPLE,
    fontSize: 16,
  },
  headingContainer: {
    // backgroundColor: 'tomato',
    marginTop: windowHeight * 0.02,
    width: windowWidth * 0.9,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heading: {
    fontFamily: Helvetica_Neue_Medium,
    color: DARK_THEME,
    fontSize: 20,
    textAlign: 'left',
    textAlignVertical: 'center',
    lineHeight: 20,
  },
  termsContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.9,
    height: windowHeight * 0.07,
    marginTop: windowHeight * 0.02,
    flexDirection: 'row',
  },
  checkboxContainer: {
    // backgroundColor: 'red',
  },
  termsTextContainer: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.8,
  },
  authcheckboxContainer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    width: windowWidth * 0.4,
    alignItems: 'center',
    // justifyContent: 's',
  },
  rememberText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    color: DARK_THEME,
    fontSize: 15,
  },
  termsText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 16,
    marginLeft: 15,
    color: DARK_THEME,
  },
  customButton: {
    backgroundColor: DISABLED,
    height: windowHeight * 0.07,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'space-around',
    borderRadius: 100,
    marginTop: windowHeight * 0.04,
    alignSelf: 'center',
    elevation: 3,
    flexDirection: 'row',
    marginBottom: 20,
  },
  lineCont: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  customButtonText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  customAuthButton: {
    backgroundColor: DARK_THEME,
    height: windowHeight * 0.07,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'space-around',
    borderRadius: 100,
    marginTop: windowHeight * 0.04,
    alignSelf: 'center',
    elevation: 3,
    flexDirection: 'row',
    marginBottom: windowHeight * 0.03,
  },
  customAuthButtonText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  modalStyles: {},
  authModalContainer: {
    backgroundColor: LIGHT_THEME,
    alignSelf: 'center',
    width: windowWidth * 0.95,
    height: windowHeight * 0.6,
    borderRadius: 20,
    // position: 'absolute',
    // top: (windowHeight * 1.0) / 4,
    // bottom: (windowHeight * 1.0) / 4,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 90,
  },
  inputContainer: {
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: windowHeight * 0.06,
    width: windowWidth * 0.8,
    borderWidth: 1,
    borderColor: DARK_THEME,
    // backgroundColor: 'tomato',
    margin: 10,
  },
  inputStyle: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 18,
    // backgroundColor: 'tomato',
    width: windowWidth * 0.7,
    color: DARK_THEME,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  forgotPassAndCheckboxContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  errorMessageTextStyle: {
    color: 'red',
    textAlign: 'center',
    // backgroundColor: 'gold',
    width: windowWidth * 0.6,
    fontFamily: Helvetica_Neue_BoldCondensed,
    alignSelf: 'center',
    fontSize: 12,
  },
  cancelButtonContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.9,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 10,
  },
});

export default styles;
