import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  DISABLED,
  Helvetica_Neue_Bold,
  Helvetica_Neue_BoldCondensed,
  Helvetica_Neue_Heavy,
  Helvetica_Neue_Medium,
  Helvetica_Neue_Regular,
  LIGHT_THEME,
  PRIMARY_PURPLE,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
  },
  headerContainer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.17,
    elevation: 6,
    justifyContent: 'flex-end',
  },
  headerBackIconContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.04,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'center',
    //     backgroundColor: 'green',
    marginRight: 50,
  },
  headerTextContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.08,
    justifyContent: 'center',
    alignSelf: 'center',
    //     backgroundColor: 'tomato',
    marginRight: 30,
  },
  headerText: {
    fontSize: 35,
    fontFamily: Helvetica_Neue_Heavy,
    color: DARK_THEME,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  customButton: {
    marginTop: 50,
    backgroundColor: DARK_THEME,
    height: windowHeight * 0.07,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    // marginTop: windowHeight * 0.04,
    alignSelf: 'center',
    elevation: 3,
  },
  customButtonText: {
    fontFamily: Helvetica_Neue_Medium,
    color: LIGHT_THEME,
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignSelf: 'center',
  },
  PaymentInputsContainer: {
    // backgroundColor: 'tomato',
    height: 'auto',
    width: windowWidth * 0.8,
    marginTop: windowHeight * 0.06,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  inputContainer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: PRIMARY_PURPLE,
    color: DARK_THEME,
    borderRadius: 5,
    paddingHorizontal: 15,
  },
  inputDateContainer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.38,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: PRIMARY_PURPLE,
    color: DARK_THEME,
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 2,
  },
  inputCvcContainer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.38,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: PRIMARY_PURPLE,
    color: DARK_THEME,
    borderRadius: 5,
    paddingHorizontal: 15,
  },
  infoContainer: {
    backgroundColor: LIGHT_THEME,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    color: DARK_THEME,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  textInfoContainer: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 15,
    textAlign: 'center',
    color: DARK_THEME,
  },
  textLabelContainer: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 15,
    textAlign: 'left',
    color: DARK_THEME,
    // backgroundColor: 'tomato',
    width: windowWidth * 0.8,
    paddingVertical: 4,
  },
  inputStyle: {
    width: windowWidth * 0.6,
    color: '#000',
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 15,
  },
  textDateContainer: {
    color: '#000',
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 15,
    paddingVertical: 13,
  },
  btnContainer: {
    backgroundColor: '#3292E0',
    alignItems: 'center',
    justifyContent: 'center',
    width: windowWidth * 0.7,
    height: windowHeight * 0.07,
    borderRadius: 40,
  },
  dateCvcContainer: {
    flexDirection: 'row',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  lablesDownContainer: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    width: windowWidth * 0.8,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textLabel1: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 15,
    textAlign: 'left',
    color: DARK_THEME,
    // backgroundColor: 'red',
    width: windowWidth * 0.38,
    paddingVertical: 4,
  },
  textLabel2: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 15,
    textAlign: 'left',
    color: DARK_THEME,
    // backgroundColor: 'red',
    width: windowWidth * 0.38,
    paddingVertical: 4,
  },
});

export default styles;
