import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  DISABLED,
  Helvetica_Neue_Bold,
  Helvetica_Neue_BoldCondensed,
  Helvetica_Neue_Heavy,
  Helvetica_Neue_Light,
  Helvetica_Neue_Medium,
  LIGHT_THEME,
  PRIMARY_PURPLE,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    // flex: 1,
    height: 'auto',
    width: windowWidth * 1.0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DARK_THEME,
  },
  headerContainer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 1.0,
    height: windowHeight * 0.17,
    elevation: 6,
    justifyContent: 'flex-end',
  },
  headerBackIconContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.04,
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'center',
    // backgroundColor: 'green',
    marginRight: 50,
  },
  headerTextContainer: {
    width: windowWidth * 0.8,
    height: windowHeight * 0.08,
    justifyContent: 'center',
    alignSelf: 'center',
    //     backgroundColor: 'tomato',
    marginRight: 30,
  },
  headerText: {
    fontSize: 35,
    fontFamily: Helvetica_Neue_Heavy,
    color: DARK_THEME,
    textAlignVertical: 'center',
    textAlign: 'left',
  },
  scrollContainer: {
    // flex: 1,
    height: windowHeight * 1.0,
    width: windowWidth * 1.0,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: 'tomato',
    // marginTop: 15,
    // marginBottom: 15,
  },

  logoContainer: {
    // backgroundColor: 'tomato',
    width: 40,
    height: 40,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    // marginTop: windowHeight * 0.02,
  },
  logoStyle: {
    // backgroundColor: 'tomato',
    width: 40,
    height: 40,
  },
  greetingTextContainer: {
    // backgroundColor: 'green',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: windowWidth * 0.7,
    marginTop: 4,
  },
  greetingText: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 20,
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 24,
    color: DARK_THEME,
  },
  orderTextContainer: {
    // backgroundColor: 'green',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: windowWidth * 0.7,
    marginTop: 4,
  },
  orderText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 24,
    color: DISABLED,
  },
  orderNoText: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 24,
    color: PRIMARY_PURPLE,
  },
  updownContainer: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.7,
    alignSelf: 'center',
    height: windowHeight * 0.75,
    justifyContent: 'space-between',
    marginTop: windowHeight * 0.02,
  },
  downContainer: {
    // backgroundColor: 'tomato',
    height: windowHeight * 0.6,
    width: windowWidth * 0.7,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  upperContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.7,
    height: windowHeight * 0.13,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headingOrderSummaryContainer: {
    // backgroundColor: 'green',
    alignSelf: 'center',
    width: windowWidth * 0.7,
    height: 'auto',
    alignItems: 'flex-start',
  },
  headingOrderSummaryText: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 20,
    textAlign: 'left',
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  breaker: {
    backgroundColor: '#EBEBEB',
    width: windowWidth * 0.7,
    height: 1,
    marginTop: windowHeight * 0.012,
    alignSelf: 'center',
  },
  dateTimeContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.7,
    height: windowHeight * 0.07,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 20,
  },
  startContainer: {
    // backgroundColor: 'cyan',
    width: windowWidth * 0.3,
    height: windowHeight * 0.05,
    alignItems: 'flex-start',
    justifyContent: 'space-evenly',
  },
  startTextContainer: {
    // backgroundColor: 'red',
    width: windowWidth * 0.3,
    alignItems: 'flex-start',
  },
  startText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 13,
    color: DISABLED,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  startDescText: {
    fontFamily: Helvetica_Neue_Medium,
    fontSize: 16,
    color: DARK_THEME,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  pickupDropoffLocationContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.7,
    height: windowHeight * 0.13,
    alignItems: 'flex-start',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  locationTextContainers: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.7,
    alignItems: 'flex-start',
    alignSelf: 'center',
  },
  locationText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 13,
    color: DISABLED,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  locationNameContainer: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.7,
    alignItems: 'flex-start',
    alignSelf: 'center',
    marginTop: 8,
  },
  locationNameText: {
    fontFamily: Helvetica_Neue_Medium,
    fontSize: 16,
    color: DARK_THEME,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  addressTextContainer: {
    // backgroundColor: 'cyan',
    width: windowWidth * 0.7,
    height: 'auto',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  addressText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 16,
    color: DARK_THEME,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  mapViewContainer: {
    backgroundColor: 'tomato',
    width: windowWidth * 0.7,
    height: windowHeight * 0.09,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    margin: 10,
  },
  imageMapVIewStyles: {
    width: windowWidth * 0.7,
    height: windowHeight * 0.1,
  },
  itemInfoContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.7,
    height: windowHeight * 0.08,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignSelf: 'center',
    // marginTop: windowHeight * 0.01,
  },
  grandTotalContainer: {
    width: windowWidth * 0.7,
    // height: windowHeight * 0.2,
    // elevation: 4,
    // borderRadius: 20,
    // marginTop: 20,
    justifyContent: 'center',
  },
  subContainer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.7,
    height: windowHeight * 0.03,
    alignSelf: 'center',
  },
  subtotalText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 16,
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  totalCost: {
    fontFamily: Helvetica_Neue_Bold,
    fontSize: 20,
    textAlignVertical: 'center',
    color: DARK_THEME,
  },
  breaker2: {
    backgroundColor: PRIMARY_PURPLE,
    width: windowWidth * 0.7,
    height: 2,
    marginTop: windowHeight * 0.01,
    marginBottom: windowHeight * 0.01,
    alignSelf: 'center',
  },
});

export default styles;
