import {StyleSheet, Dimensions} from 'react-native';
import {
  DARK_THEME,
  DISABLED,
  Helvetica_Neue_Bold,
  Helvetica_Neue_BoldCondensed,
  Helvetica_Neue_Medium,
  INPUT_BORDER_COLOR,
  LIGHT_THEME,
  PRIMARY_PURPLE,
} from '../../helper/commonStyle';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    // flex: 1,
    width: windowWidth * 1.0,
    height: windowHeight * 1.0,
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: LIGHT_THEME,
  },
  inputContainer: {
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: windowHeight * 0.07,
    width: windowWidth * 0.95,
    // borderWidth: 0.5,
    // borderColor: INPUT_BORDER_COLOR,
    // backgroundColor: 'tomato',
    alignSelf: 'center',
  },
  dropdown: {
    height: 50,
    borderRadius: 7,
    paddingHorizontal: 17,
    backgroundColor: LIGHT_THEME,
    // elevation: 1,
    width: windowWidth * 0.45,
    alignSelf: 'center',
    margin: 5,
  },
  placeholderStyle: {
    fontSize: 18,
    fontFamily: Helvetica_Neue_BoldCondensed,
    color: '#737373',
  },
  selectedTextStyle: {
    fontSize: 18,
    fontFamily: Helvetica_Neue_BoldCondensed,
    color: '#737373',
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  containerrrrStyle: {
    marginTop: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 100,
    elevation: 10,
  },
  inputIconContainer: {
    //     backgroundColor: 'tomato',
    height: 20,
    width: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  breaker: {
    // backgroundColor: 'red',
    margin: 12,
  },
  breakerINLine: {
    width: windowWidth * 0.75,
    borderWidth: 0.2,
    borderColor: '#EBEBEB',
  },
  falteContainer: {
    // flex: 1,
    // marginTop: windowHeight * 0.02,
    height: windowHeight * 1.0,
    width: windowWidth * 0.95,
    // paddingTop: 10,
    // paddingBottom: 10,
  },
  OrderHistoryContianer: {
    backgroundColor: LIGHT_THEME,
    width: windowWidth * 0.9,
    height: windowHeight * 0.2,
    elevation: 4,
    borderRadius: 20,
    margin: 5,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  pickupDetails: {
    // backgroundColor: 'gold',
    width: windowWidth * 0.8,
    height: windowHeight * 0.06,
    alignSelf: 'center',
    marginTop: 20,
  },
  orderTypecontainer: {
    flexDirection: 'row',
    // backgroundColor: 'gold',
    width: windowWidth * 0.8,
    height: windowHeight * 0.03,
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderTypeHeading: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    color: DISABLED,
    fontSize: 14,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  orderType: {
    fontFamily: Helvetica_Neue_Bold,
    color: PRIMARY_PURPLE,
    fontSize: 14,
    textAlign: 'right',
    textAlignVertical: 'center',
  },
  orderNumberContainer: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    // backgroundColor: 'red',
    height: windowHeight * 0.03,
  },
  orderNumberText: {
    fontFamily: Helvetica_Neue_Medium,
    color: DARK_THEME,
    fontSize: 14,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  dateTimeContainer: {
    // backgroundColor: 'green',
    width: windowWidth * 0.8,
    height: windowHeight * 0.06,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
    marginBottom: 20,
  },
  startContainer: {
    // backgroundColor: 'cyan',
    width: windowWidth * 0.3,
    height: windowHeight * 0.05,
    alignItems: 'flex-start',
    justifyContent: 'space-evenly',
  },
  startTextContainer: {
    // backgroundColor: 'red',
    width: windowWidth * 0.3,
    alignItems: 'flex-start',
  },
  startText: {
    fontFamily: Helvetica_Neue_BoldCondensed,
    fontSize: 13,
    color: DISABLED,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  startDescText: {
    fontFamily: Helvetica_Neue_Medium,
    fontSize: 16,
    color: DARK_THEME,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
});

export default styles;
